### API SERVER
GET http://localhost:8000/

### Users API
#### Get all users

GET http://localhost:8000/user

### Get more user information
GET http://localhost:8000/usersInfo

#### Get user by id

GET http://localhost:8000/user/1

#### Create user

POST http://localhost:8000/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4NjU0Njc2fQ._x5CbNxSVc7FHJy9vr30YckpL7-EG-DIpvbrcDtfiYY
Content-Type: application/json

{
    "name": "Icily Weird",
    "contact_phone": "0742068702",
    "contact_verified": "true",
    "email": "weirdicily@mail.com",
    "email_verified": "true",
    "confirmation_code": "XSVMKNH",
    "password": "ice5"
}

#### Update user

PUT http://localhost:8000/user/1
Content-Type: application/json

{
    "name": "Kevin Kevo",
}

#### Delete user

DELETE http://localhost:8000/user/10

Authorization: ""

### States API
#### Get all states

GET http://localhost:8000/state

### Get more state information
GET http://localhost:8000/statesInfo

#### Get state by id

GET http://localhost:8000/state/1

#### Create state

POST http://localhost:8000/state
Content-Type: application/json

{
    "name": "Nairobi",
    "code" : "NRB"
}

#### Update state

PUT http://localhost:8000/state/1
Content-Type: application/json

{
    "name": "Nairobi City",
}

#### Delete state

DELETE http://localhost:8000/state/10

Authorization: ""

### City API
#### Get all cities

GET http://localhost:8000/city

### Get more city information
GET http://localhost:8000/cityInfo

#### Get city by id

GET http://localhost:8000/city/1

#### Create city

POST http://localhost:8000/city
Content-Type: application/json

{
    "name": "Nairobi",
    "state_id" : 1
}

#### Update city

PUT http://localhost:8000/city/1
Content-Type: application/json

{
    "name": "Nairobi City",
}

#### Delete city

DELETE http://localhost:8000/city/10

Authorization:""

### Address API
#### Get all addresses

GET http://localhost:8000/address

### Get more address information
GET http://localhost:8000/addressInfo

#### Get address by id

GET http://localhost:8000/address/1

#### Create address

POST http://localhost:8000/address
Content-Type: application/json

{
    "address": "Tom Mboya Street",
    "city_id" : 1
}

#### Update address

PUT http://localhost:8000/address/1
Content-Type: application/json

{
    "address": "Tom Mboya Street",
}

#### Delete address

DELETE http://localhost:8000/address/10

Authorization:""

### Restaurant API
#### Get all restaurants

GET http://localhost:8000/restaurant

### Get more restaurant information
GET http://localhost:8000/restaurantInfo

#### Get restaurant by id

GET http://localhost:8000/restaurant/1

#### Create restaurant

POST http://localhost:8000/restaurant
Content-Type: application/json

{
    "name": "Java",
    "address_id" : 1
}

#### Update restaurant

PUT http://localhost:8000/restaurant/1
Content-Type: application/json

{
    "name": "Java House",
}

#### Delete restaurant

DELETE http://localhost:8000/restaurant/10

Authorization:""

### Restaurant Owner API
#### Get all restaurant owners

GET http://localhost:8000/restaurant_owner

### Get more restaurant owner information
GET http://localhost:8000/restuarantOwnerInfo

#### Get restaurant owner by id

GET http://localhost:8000/restaurant_owner/1

#### Create restaurant owner

POST http://localhost:8000/restaurant_owner
Content-Type: application/json

{
    "user_id": 1,
    "restaurant_id" : 1
}

#### Update restaurant owner

PUT http://localhost:8000/restaurant_owner/1
Content-Type: application/json

{
    "user_id": 1,
}

#### Delete restaurant owner

DELETE http://localhost:8000/restaurant_owner/10

Authorization:""

### category API
#### Get all categories

GET http://localhost:8000/category

### Get more category information
GET http://localhost:8000/categoryInfo/1


#### Get category by id

GET http://localhost:8000/category/1

#### Create category

POST http://localhost:8000/category
Content-Type: application/json

{
    "name": "Fast Food",
}

#### Update category

PUT http://localhost:8000/category/1
Content-Type: application/json

{
    "name": "Fast Food",
}

#### Delete category

DELETE http://localhost:8000/category/10

Authorization:""

### Menu Items API
#### Get all menu items

GET http://localhost:8000/menu_items

#### Get more menu items information
GET http://localhost:8000/menuInfo

#### Get menu item by id

GET http://localhost:8000/menu_items/1

#### Create menu item

POST http://localhost:8000/menu_items
Content-Type: application/json

{
    "name": "Chicken Burger",
    "price": 500,
    "category_id": 1,
    "restaurant_id": 1
}

#### Update menu item

PUT http://localhost:8000/menu_items/1
Content-Type: application/json

{
    "name": "Chicken Burger",
}

#### Delete menu item

DELETE http://localhost:8000/menu_items/10

Authorization:""

### Orders API
#### Get all orders

GET http://localhost:8000/orders

#### Get more orders information
GET http://localhost:8000/OrderInfo

#### Get order by id

GET http://localhost:8000/orders/1

#### Create order

POST http://localhost:8000/orders
Content-Type: application/json

{
    "user_id": 1,
    "restaurant_id": 1,
    "total_price": 500,
    "status": "pending"
}

#### Update order

PUT http://localhost:8000/orders/1
Content-Type: application/json

{
    "status": "completed",
}

#### Delete order

DELETE http://localhost:8000/orders/10

Authorization:""

### Order Menu Item API
#### Get all order menu items

GET http://localhost:8000/order_menu_item

#### Get more order menu items information
GET http://localhost:8000/menuOrdersInfo

#### Get order menu item by id

GET http://localhost:8000/order_menu_item/1

#### Create order menu item

POST http://localhost:8000/order_menu_item
Content-Type: application/json

{
    "order_id": 1,
    "menu_item_id": 1,
    "quantity": 2
}

#### Update order menu item

PUT http://localhost:8000/order_menu_item/1
Content-Type: application/json

{
    "quantity": 3,
}

#### Delete order menu item

DELETE http://localhost:8000/order_menu_item/10

Authorization:""

### Drivers API
#### Get all drivers

GET http://localhost:8000/drivers

#### Get more drivers information
GET http://localhost:8000/driverInfo

#### Get driver by id

GET http://localhost:8000/drivers/1

#### Create driver

POST http://localhost:8000/drivers
Content-Type: application/json

{
    "car_make": "Toyota",
    "car_model": "Vitz",
    "car_year": 2010,
    "user_id": 1,
    "online": true,
    "delivering": false
}

#### Update driver

PUT http://localhost:8000/drivers/1
Content-Type: application/json

{
    "online": false,
}

#### Delete driver

DELETE http://localhost:8000/drivers/10

Authorization:""

### Orders Status API
#### Get all orders status

GET http://localhost:8000/orders_status

#### Get more orders status information
GET http://localhost:8000/orderStatusInfo

#### Get order status by id

GET http://localhost:8000/orders_status/1

#### Create order status

POST http://localhost:8000/orders_status
Content-Type: application/json

{
    "order_id": 1,
    "status": "pending"
}

#### Update order status

PUT http://localhost:8000/orders_status/1
Content-Type: application/json

{
    "status": "completed",
}

#### Delete order status

DELETE http://localhost:8000/orders_status/10

Authorization:""

### status catalog API
#### Get all status catalog

GET http://localhost:8000/status_catalog

#### Get more status catalog information
GET http://localhost:8000/statusCatalog

#### Get status catalog by id

GET http://localhost:8000/status_catalog/1

#### Create status catalog

POST http://localhost:8000/status_catalog
Content-Type: application/json

{
    "name": "pending"
}

#### Update status catalog

PUT http://localhost:8000/status_catalog/1
Content-Type: application/json

{
    "name": "completed",
}

#### Delete status catalog  

DELETE http://localhost:8000/status_catalog/10

Authorization:""

### Comments API
#### Get all comments

GET http://localhost:8000/comments

#### Get more comments information
GET http://localhost:8000/comments/2

#### Get comment by id

GET http://localhost:8000/comments/1

#### Create comment

POST http://localhost:8000/comments
Content-Type: application/json

{
    "user_id": 1,
    "restaurant_id": 1,
    "comment": "The food was great"
}

#### Update comment

PUT http://localhost:8000/comments/1
Content-Type: application/json

{
    "comment": "The food was amazing",
}

#### Delete comment 

DELETE http://localhost:8000/comments/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJ1c2VybmFtZSI6IkpvaG4iLCJleHAiOjE3MTgyOTU1NTl9.8eMiCcKVFNEyagOE9L4xu_LJJ8DqGBoBrXkhooWA3rE


### Auth API
#### Register 

POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "user_id": 24,
    "username": "Icily",
    "password": "ice5",
    "role": "user"
}

#### Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "John",
    "password": "kim1"
}


###

























































